# Generated by Django 5.1.3 on 2025-02-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_compra_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comentario", models.TextField()),
                ("motivo", models.TextField()),
                ("nota", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.categoria")),
                ("editora", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.editora")),
                ("livro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.livro")),
            ],
        ),
    ]
