# Generated by Django 5.1.3 on 2025-02-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_avaliacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="motivo",
        ),
    ]
