# Generated by Django 5.1.3 on 2025-02-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_avaliacao_motivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="motivo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="categoria",
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to="core.categoria"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="editora",
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to="core.editora"),
        ),
    ]
