# Generated by Django 5.1.3 on 2025-02-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_avaliacao_motivo_alter_avaliacao_categoria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="motivo",
        ),
    ]
